# Generated by Django 2.2.12 on 2020-11-23 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('wac', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], help_text='Withnell Water or not', max_length=1)),
                ('postcode', models.CharField(max_length=10, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fishy.Venue')),
            ],
            options={
                'ordering': ['-date', 'venue'],
            },
        ),
        migrations.CreateModel(
            name='Catch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(help_text='Weight in ounces')),
                ('weighed', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', help_text='Weighed (if N = estimated)', max_length=1)),
                ('method', models.CharField(choices=[('F', 'Float'), ('L', 'Ledger'), ('M', 'Method Feeder')], default='F', help_text='Method used for catch', max_length=1)),
                ('catch_time', models.DateTimeField(auto_now_add=True)),
                ('photo', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('bait', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fishy.Bait')),
                ('fish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fishy.Fish')),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fishy.Trip')),
            ],
            options={
                'ordering': ['trip', '-catch_time', '-weight', 'fish'],
            },
        ),
    ]
