# Generated by Django 2.2.12 on 2020-06-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catch',
            name='method',
            field=models.CharField(choices=[('F', 'Float'), ('L', 'Ledger')], default='F', help_text='Method used for catch', max_length=1),
        ),
        migrations.AlterField(
            model_name='catch',
            name='weighed',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', help_text='Weighed (if N = estimated)', max_length=1),
        ),
        migrations.AlterField(
            model_name='catch',
            name='weight',
            field=models.IntegerField(help_text='Weight in ounces'),
        ),
    ]
