# Generated by Django 2.2.12 on 2020-06-03 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishy', '0002_auto_20200602_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['date', 'venue']},
        ),
    ]
