# Generated by Django 2.2.12 on 2020-06-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishy', '0003_auto_20200603_0936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-date', 'venue']},
        ),
    ]
