# Generated by Django 2.2.12 on 2020-06-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishy', '0004_auto_20200603_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='postcode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
