# Generated by Django 2.2.12 on 2020-06-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishy', '0005_venue_postcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catch',
            options={'ordering': ['trip', 'fish', '-weight']},
        ),
    ]
