# Generated by Django 2.2.12 on 2020-08-19 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fishy', '0006_auto_20200603_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catch',
            options={'ordering': ['trip', '-weight', 'fish']},
        ),
        migrations.AddField(
            model_name='catch',
            name='catch_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
