# Generated by Django 2.2.12 on 2020-08-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishy', '0007_auto_20200819_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catch',
            options={'ordering': ['trip', '-catch_time', '-weight', 'fish']},
        ),
        migrations.AlterField(
            model_name='catch',
            name='method',
            field=models.CharField(choices=[('F', 'Float'), ('L', 'Ledger'), ('M', 'Method Feeder')], default='F', help_text='Method used for catch', max_length=1),
        ),
    ]
