# Generated by Django 2.2.12 on 2020-10-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishy', '0008_auto_20200827_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='catch',
            name='photo',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
